### ISSUE TITLE
unable to run tasks

### ISSUE THREAD

**Issue by rednaks** [alf149/ansible-role-crowdsec#4]
I was trying to execute the tasks but doesn't seem working, is it an issue with the ansible version ?
my ansible version: 
```
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]

```

logs: 
```
ERROR! this task 'ansible.builtin.shell' has extra params, which is only allowed in the following modules: meta, import_tasks, include_tasks, win_command, add_host, win_shell, raw, shell, import_role, include_vars, set_fact, group_by, include, command, include_role, script

The error appears to be in '/home/ubuntu/.ansible/roles/alf149.crowdsec/tasks/main.yml': line 144, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Crowdsec cscli bash completion
  ^ here

```

**Comment by alf149** [comment]
Sorry for the late answer. Hope this information helps. 

On my pop_os test PC 

I installed ansible with 
sudo apt update && sudo apt install python3-pip
sudo pip3 install ansible 

running ansible --version
gives me this output:
ansible [core 2.12.1]
  config file = /home/USER/Documents/git/ansible/lab/ansible.cfg
  configured module search path = ['/home/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/USER/Documents/git/ansible/lab/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
